apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/test-project-225703/nodeapp:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000